---
-
  hosts: ubuntu-c
  tasks:
    - name: Pull images
      docker_image:
        name: "{{ item }}"
        source: pull
      with_items:
        - centos
        - ubuntu
        - redis
        - nginx
        - wernight/funbox
...
